context:
  name: gget
  version: "0.30.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/de/47/92871c1103dd88a4189efa90deb8290dd6180cbfb74d01c423930d3553ad/gget-${{ version }}.tar.gz
  sha256: 94d44fa131cd54ca88ee95a934e3ce2ca3db14fbcb7cdb1293906949656d239a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - gget=gget.main:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    # NOTE: the lib is being imported during the package build
    - numpy >=1.17.2
    - pandas >=1.0.0
    - requests >=2.22.0
    - ipython
    - matplotlib-base
    - mysql-connector-python >=8.0.32
    - beautifulsoup4 >=4.10.0
    - ipywidgets
    - tqdm
    - lxml
  run:
    - python >=${{ python_min }}
    - numpy >=1.17.2
    - pandas >=1.0.0
    - requests >=2.22.0
    - ipython
    - matplotlib-base
    - mysql-connector-python >=8.0.32
    - beautifulsoup4 >=4.10.0
    - ipywidgets
    - tqdm
    - lxml

tests:
  - python:
      imports:
        - gget
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - gget ref --help

about:
  summary: Efficient querying of genomic databases.
  license: Apache-2.0 AND GPL-3.0-only AND BSD-2-Clause
  license_file:
    - LICENSE
    - gget/bins/Darwin/license.txt
    - gget/bins/alphafold/LICENSE
    - gget/bins/alphafold/NOTICE
    - gget/bins/Windows/license.txt
    - gget/bins/Linux/license.txt
  homepage: https://github.com/pachterlab/gget

extra:
  recipe-maintainers:
    - hadim
